---
name: Build Workflow

on:
  workflow_call:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: ⏬ Checkout repo
        uses: actions/checkout@v6

      - name: 🔄 Init PNPM
        uses: ./.github/actions/pnpm

      - name: 🔨 Build
        run: pnpm run build

      - name: ⏫ Upload build
        uses: actions/upload-artifact@v7
        with:
          name: frontend-build
          path: dist
